// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByMOXFjPxmMN-tfFprr00FHf4qaaxAVZ0',
    appId: '1:831986672203:web:a96f67f8cd25dc1240e3ce',
    messagingSenderId: '831986672203',
    projectId: 'cripto-firebase-372921',
    authDomain: 'cripto-firebase-372921.firebaseapp.com',
    storageBucket: 'cripto-firebase-372921.appspot.com',
    measurementId: 'G-SC0NV9MNBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXY8a-M6KwLBVmwGOZFBb3BtTz63_fGXw',
    appId: '1:831986672203:android:820a5021be8f76d440e3ce',
    messagingSenderId: '831986672203',
    projectId: 'cripto-firebase-372921',
    storageBucket: 'cripto-firebase-372921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwLDoHLmkJPFedJJxb3QJcQzp8teYwBR8',
    appId: '1:831986672203:ios:876ecadbdd214c5b40e3ce',
    messagingSenderId: '831986672203',
    projectId: 'cripto-firebase-372921',
    storageBucket: 'cripto-firebase-372921.appspot.com',
    iosClientId: '831986672203-00l5ic2m9q81cqpuh1aochlvvmhj8u8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.criptoMoedas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwLDoHLmkJPFedJJxb3QJcQzp8teYwBR8',
    appId: '1:831986672203:ios:876ecadbdd214c5b40e3ce',
    messagingSenderId: '831986672203',
    projectId: 'cripto-firebase-372921',
    storageBucket: 'cripto-firebase-372921.appspot.com',
    iosClientId: '831986672203-00l5ic2m9q81cqpuh1aochlvvmhj8u8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.criptoMoedas',
  );
}
