// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSUuzsaS3qaInwS2ge9425jqWjXXhbSuc',
    appId: '1:142152035556:web:0788dabd6a99eb2e7e10f1',
    messagingSenderId: '142152035556',
    projectId: 'fire-base-teste-edc42',
    authDomain: 'fire-base-teste-edc42.firebaseapp.com',
    storageBucket: 'fire-base-teste-edc42.appspot.com',
    measurementId: 'G-D4P1MSC8PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKSO-0cdee0Pvp-GUMYhka9aRHjEgHmJY',
    appId: '1:142152035556:android:d6bcb3e3e8aa476a7e10f1',
    messagingSenderId: '142152035556',
    projectId: 'fire-base-teste-edc42',
    storageBucket: 'fire-base-teste-edc42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSaT3ciF83ZkIESybqyvkO8haklqcbWcA',
    appId: '1:142152035556:ios:61d58e7c330660c97e10f1',
    messagingSenderId: '142152035556',
    projectId: 'fire-base-teste-edc42',
    storageBucket: 'fire-base-teste-edc42.appspot.com',
    iosClientId: '142152035556-mf6dm47fk0h3kdg7i2j7gpulfs5cohdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.criptoMoedas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSaT3ciF83ZkIESybqyvkO8haklqcbWcA',
    appId: '1:142152035556:ios:61d58e7c330660c97e10f1',
    messagingSenderId: '142152035556',
    projectId: 'fire-base-teste-edc42',
    storageBucket: 'fire-base-teste-edc42.appspot.com',
    iosClientId: '142152035556-mf6dm47fk0h3kdg7i2j7gpulfs5cohdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.criptoMoedas',
  );
}
